import React,{useEffect,useState} from 'react';
import ReactDOM from 'react-dom/client';
import {BrowserRouter,Routes,Route,Link,Navigate,useNavigate} from 'react-router-dom';
import {createClient} from '@supabase/supabase-js';
import './styles/global.css';

const configured=Boolean(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_ANON_KEY);
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||'https://placeholder.supabase.co',import.meta.env.VITE_SUPABASE_ANON_KEY||'placeholder');

const demo=[
{id:'1',name_zh:'柔感綁帶上衣',name_en:'Soft Tie Top',description_zh:'小量手工製作，使用柔軟棉麻布料。',description_en:'Handmade in small batches with soft cotton-linen fabric.',price:1280,stock:6,status:'active',images:['https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80']},
{id:'2',name_zh:'弧線長裙',name_en:'Curve Long Skirt',description_zh:'高腰弧線剪裁與自然垂墜輪廓。',description_en:'A curved high-waisted silhouette with natural drape.',price:1680,stock:3,status:'active',images:['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1200&q=80']}
];

function Store(){const[lang,setLang]=useState(localStorage.getItem('923-lang')||'zh');const[products,setProducts]=useState(demo);useEffect(()=>{localStorage.setItem('923-lang',lang)},[lang]);useEffect(()=>{if(!configured)return;(async()=>{const{data}=await supabase.from('products').select('*,product_images(image_url,sort_order)').eq('status','active');if(data)setProducts(data.map(p=>({...p,images:(p.product_images||[]).sort((a,b)=>a.sort_order-b.sort_order).map(i=>i.image_url)})))} )()},[]);const zh=lang==='zh';return <><div className="announcement">SMALL BATCH · HANDMADE IN TAIWAN</div><header><Link className="logo" to="/">9·2·3<span>HANDMADE STUDIO</span></Link><nav><a href="#products">{zh?'本期新品':'New Arrivals'}</a><a href="#story">{zh?'品牌故事':'Our Story'}</a></nav><div className="actions"><button onClick={()=>setLang(zh?'en':'zh')}>{zh?'EN':'中文'}</button><Link to="/login">{zh?'會員登入':'Customer Login'}</Link><button>{zh?'購物車':'Cart'} (0)</button></div></header><main><section className="hero"><div className="hero-copy"><p className="eyebrow">923 · DROP 01</p><h1>{zh?'簡單穿，\n但不簡單。':'Simple to wear.\nNever ordinary.'}</h1><p>{zh?'日常輪廓、柔和色彩與手工細節。每次只做一點，讓每一件都更靠近你。':'Everyday silhouettes, gentle colors and handmade details, created slowly in small batches.'}</p><a className="primary" href="#products">{zh?'查看新品':'Shop New Arrivals'}</a></div><div className="hero-art"><div className="morse"><small>NINE TWO THREE</small><strong>— — — — ·</strong><strong>· · — — —</strong><strong>· · · — —</strong><small>MADE SLOWLY</small></div></div></section><section id="products" className="products"><p className="eyebrow">NEW ARRIVALS</p><h2>{zh?'本期新品':'New Arrivals'}</h2><div className="grid">{products.map(p=><article key={p.id}><img src={p.images?.[0]} /><div className="meta"><div><h3>{zh?p.name_zh:p.name_en}</h3><p>{zh?p.description_zh:p.description_en}</p></div><strong>NT${Number(p.price).toLocaleString()}</strong></div><button className="secondary">{zh?'加入購物車':'Add to Cart'}</button></article>)}</div></section><section id="story" className="story"><div className="number">923</div><div><p className="eyebrow">OUR STORY</p><h2>{zh?'兩個人，一件一件慢慢做。':'Two people, making every piece slowly.'}</h2><p>{zh?'923 是一個小量手工服飾品牌。我們希望衣服不只好看，也保留製作者的痕跡。':'923 is a small-batch handmade clothing label. Every detail is shaped with care.'}</p></div></section></main><footer><strong>923</strong><p>Handmade Clothing Studio · Taiwan</p></footer></>}

function Login({admin=false}){const nav=useNavigate();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[msg,setMsg]=useState('');async function submit(e){e.preventDefault();if(!configured)return setMsg('尚未連接 Supabase，請先依 README 設定。');const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error||!data.user)return setMsg(error?.message||'登入失敗');if(admin){const{data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();if(profile?.role!=='admin'){await supabase.auth.signOut();return setMsg('此帳號不是店家管理員。')}nav('/admin')}else nav('/account')}return <div className={admin?'admin-login':'customer-login'}><form onSubmit={submit}><Link className="logo" to="/">9·2·3<span>{admin?'STORE ADMIN':'CUSTOMER ACCOUNT'}</span></Link><p className="eyebrow">{admin?'PRIVATE ACCESS':'CUSTOMER LOGIN'}</p><h1>{admin?'店家後台登入':'會員登入'}</h1><p>{admin?'顧客帳號無法進入這個獨立後台。':'此區只提供顧客登入，不顯示店家管理功能。'}</p><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>密碼<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{msg&&<div className="message">{msg}</div>}<button className="primary" type="submit">登入</button><Link to="/">返回商店</Link></form></div>}

function ProtectedAdmin({children}){const[state,setState]=useState('loading');useEffect(()=>{(async()=>{if(!configured)return setState('denied');const{data}=await supabase.auth.getUser();if(!data.user)return setState('denied');const{data:p}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();setState(p?.role==='admin'?'ok':'denied')})()},[]);if(state==='loading')return <div className="center">驗證店家權限中…</div>;if(state==='denied')return <Navigate to="/admin/login" replace/>;return children}

function Admin(){const nav=useNavigate();const[tab,setTab]=useState('總覽');const[products,setProducts]=useState([]);const[form,setForm]=useState({name_zh:'',name_en:'',description_zh:'',description_en:'',price:0,stock:0,category:'tops'});async function load(){const{data}=await supabase.from('products').select('*').order('created_at',{ascending:false});setProducts(data||[])}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();const slug=(form.name_en||form.name_zh).toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]+/g,'-')+'-'+Date.now();await supabase.from('products').insert({...form,slug,status:'draft',featured:false});setForm({name_zh:'',name_en:'',description_zh:'',description_en:'',price:0,stock:0,category:'tops'});load()}async function logout(){await supabase.auth.signOut();nav('/admin/login')}return <div className="admin-layout"><aside><div className="admin-brand">923<span>STORE ADMIN</span></div>{['總覽','商品管理','訂單管理','顧客管理','網站內容','品牌故事','網站配色','設定'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<button className="logout" onClick={logout}>登出店家</button></aside><main><div className="top"><div><p className="eyebrow">923 ADMINISTRATION</p><h1>{tab}</h1></div><a href="/" target="_blank">預覽顧客網站 ↗</a></div>{tab==='總覽'&&<><div className="stats"><article><span>今日營業額</span><strong>NT$0</strong></article><article><span>待處理訂單</span><strong>0</strong></article><article><span>上架商品</span><strong>{products.filter(p=>p.status==='active').length}</strong></article><article><span>商品草稿</span><strong>{products.filter(p=>p.status==='draft').length}</strong></article></div><section className="panel"><h2>前後台已完全分離</h2><p>顧客登入與店家登入使用不同網址、不同介面與資料庫角色驗證。</p></section></>}{tab==='商品管理'&&<div className="columns"><form className="panel" onSubmit={add}><h2>新增商品草稿</h2>{[['name_zh','中文商品名稱'],['name_en','English name'],['description_zh','中文說明'],['description_en','English description']].map(([k,l])=><label key={k}>{l}{k.includes('description')?<textarea value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>:<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>}</label>)}<div className="row"><label>價格<input type="number" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label>庫存<input type="number" value={form.stock} onChange={e=>setForm({...form,stock:Number(e.target.value)})}/></label></div><button className="primary">建立商品</button></form><section className="panel"><h2>商品清單</h2>{products.map(p=><div className="product-row" key={p.id}><div><strong>{p.name_zh}</strong><span>{p.name_en}</span></div><div>NT${p.price} · {p.status}</div></div>)}</section></div>}{!['總覽','商品管理'].includes(tab)&&<section className="panel coming"><p className="eyebrow">NEXT DEVELOPMENT STEP</p><h2>{tab}</h2><p>此模組已保留在正式架構中，下一輪會在同一套網站繼續完成。</p></section>}</main></div>}

function Account(){return <div className="center"><div><p className="eyebrow">CUSTOMER ACCOUNT</p><h1>會員中心</h1><p>顧客訂單、收藏與地址將在下一階段接上。</p><Link to="/">返回商店</Link></div></div>}
function App(){return <Routes><Route path="/" element={<Store/>}/><Route path="/login" element={<Login/>}/><Route path="/account" element={<Account/>}/><Route path="/admin/login" element={<Login admin/>}/><Route path="/admin" element={<ProtectedAdmin><Admin/></ProtectedAdmin>}/><Route path="*" element={<Navigate to="/"/>}/></Routes>}
ReactDOM.createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
